language: python
dist: trusty
sudo: required
python:
  - "2.7"
env:
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.10.5 DB=sqlite

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - ls -al
  - cd MyLang
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test